CREATE TABLE briefing_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    briefing_date DATE NOT NULL UNIQUE,
    lead VARCHAR(600) NOT NULL,
    read_minutes INTEGER NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_verified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    pipeline_generated BOOLEAN,
    editorial_state VARCHAR(32),
    approved_at TIMESTAMP WITH TIME ZONE,
    approved_by VARCHAR(80),
    editorial_pass_applied BOOLEAN,
    editorial_model VARCHAR(80),
    editorial_duration_millis BIGINT,
    editorial_fallback_reason VARCHAR(600)
);

CREATE TABLE news_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES briefing_editions(id) ON DELETE CASCADE,
    category VARCHAR(32) NOT NULL,
    title VARCHAR(300) NOT NULL,
    summary VARCHAR(1200) NOT NULL,
    one_line_summary VARCHAR(400),
    why_it_matters VARCHAR(700) NOT NULL,
    what_to_watch VARCHAR(500),
    verification_status VARCHAR(32) NOT NULL,
    quality_score INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    uncertainty VARCHAR(600),
    editorial_state VARCHAR(32)
);

CREATE TABLE news_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES news_stories(id) ON DELETE CASCADE,
    statement VARCHAR(700) NOT NULL,
    source_indexes VARCHAR(120) NOT NULL,
    display_order INTEGER NOT NULL
);

CREATE TABLE news_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL REFERENCES news_stories(id) ON DELETE CASCADE,
    publisher VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    primary_source BOOLEAN NOT NULL
);

CREATE TABLE story_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL,
    detail VARCHAR(600),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_story_feedback_user_created ON story_feedback(user_id, created_at);
CREATE INDEX idx_story_feedback_story_user ON story_feedback(story_id, user_id);

CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(80) NOT NULL,
    endpoint_hash VARCHAR(64) NOT NULL UNIQUE,
    endpoint VARCHAR(3000) NOT NULL,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    delivery_hour INTEGER NOT NULL,
    delivery_minute INTEGER NOT NULL,
    weekdays VARCHAR(32) NOT NULL,
    user_agent VARCHAR(500),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_sent_at TIMESTAMP WITH TIME ZONE,
    onboarding_preview_sent_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(600)
);
CREATE INDEX idx_push_owner ON push_subscriptions(owner_id);

CREATE TABLE subscription_metric_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active_subscriptions INTEGER NOT NULL,
    reason VARCHAR(64) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE editorial_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64),
    target_id BIGINT,
    actor VARCHAR(80) NOT NULL,
    detail VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_audit_created_at ON editorial_audit_logs(created_at);

CREATE TABLE story_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id BIGINT NOT NULL,
    before_text VARCHAR(800) NOT NULL,
    after_text VARCHAR(800) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    corrected_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_correction_story ON story_corrections(story_id);

CREATE TABLE push_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    state VARCHAR(32) NOT NULL,
    attempts INTEGER NOT NULL,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    error VARCHAR(600),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_delivery_edition_subscription UNIQUE (edition_id, subscription_id)
);
CREATE INDEX idx_delivery_created_at ON push_delivery_attempts(created_at);

CREATE TABLE reader_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(80) NOT NULL UNIQUE,
    categories VARCHAR(300) NOT NULL,
    digest_size VARCHAR(16) NOT NULL,
    weekdays VARCHAR(32) NOT NULL,
    consent BOOLEAN NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE reader_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(32) NOT NULL,
    edition_id BIGINT NOT NULL,
    story_id BIGINT,
    actor_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_reader_event_created ON reader_events(created_at);
CREATE INDEX idx_reader_event_edition ON reader_events(edition_id);
CREATE INDEX idx_reader_event_actor ON reader_events(actor_hash);
